# Set default terminal
set -g default-terminal "screen-256color"

# remap prefix from 'C-b' to 'C-s'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Split panes
bind i split-window -v
bind o split-window -h
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
# Last four are for holding ctrl with modifier
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D
bind C-h select-pane -L
bind C-l select-pane -R
bind C-k select-pane -U
bind C-j select-pane -D

# reload config file 
bind r source-file ~/.tmux.conf

# Close and reopen pane
bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s $.0
bind-key '#' join-pane -hs $.0

# Try out mouse scrolling for a while
set -g mouse on

# STYLING
# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=indigo'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=yellow bg=orange bold'
